version: '3.1'

services:

  app:
    container_name: my-app
    image: my-app-img
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: our-sql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emp
    ports:
      - 3306:3306
